[tools]
node = "24"
pnpm = "latest"

[settings]
experimental = true

[tasks.puppeteer-install-chrome]
run = "pnpm exec puppeteer browsers install chrome"

[hooks]
postinstall = { task = "puppeteer-install-chrome" }
